version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      -  npm i
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - npm run test
  post_build:
    commands:
      - echo Build completed on `date`
# artifacts:
#   files:
#     - target/messageUtil-1.0.jar
